### ISSUE TITLE
Review pages in "About" menu

### ISSUE THREAD

**Issue by maneesha** [LibraryCarpentry/librarycarpentry.org#30]
The "About" menu includes the pages:

- About us
- Curriculum Advisors
- Governance

See: https://lc-new-website.netlify.app/

**Comment by tobyhodges** [comment]
* [x] on https://carp-new-website.netlify.app/about-us/, we say "Also in 2014, Library Carpentry was founded with the mission of teaching data skills to people working in library- and information-related roles." So I think ["Since 2015"](https://lc-new-website.netlify.app/about-us/) should be changed to "Since 2014" for consistency. I must have got my dates wrong, and I doubt anyone will come fact-checking us anyway.
* [x] https://lc-new-website.netlify.app/about-us/curriculum-advisors/ still contains the (delicious) placeholder text, should be updated to equivalent of what's at the top of https://dc-new-website.netlify.app/about-us/curriculum-advisors/ but with the two instances of "Data Carpentry" -> "Library Carpentry"
* [x] same as above for https://lc-new-website.netlify.app/about-us/governance/

**Comment by maneesha** [comment]
@tobyhodges  Can you review the changes I made? If it all looks good to you, please close this issue. Otherwise you can note any other changes here.

**Comment by tobyhodges** [comment]
Thanks @maneesha. The introductory text on the Curriculum Advisors page says "Data Carpentry", which should be adjusted to "Library Carpentry" but otherwise this all looks good. Please go ahead and close the issue after that adjustment has been made.
